services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: localdev

    volumes:
      - ~/.github:/home/vscode/.github:cached
      - ~/.claude:/home/vscode/.claude:cached
      - ~/.claude.json:/home/vscode/.claude.json:cached
